anzu: update port, fix display and touchscreen

diff --git a/aports/device/linux-semc-anzu/APKBUILD b/aports/device/linux-semc-anzu/APKBUILD
--- a/aports/device/linux-semc-anzu/APKBUILD
+++ b/aports/device/linux-semc-anzu/APKBUILD
@@ -1,99 +1,88 @@
-# APKBUILD based on linux-lg-mako.
-# Kernel config based on: arch/arm/configs/semc_anzu_defconfig
+# APKBUILD automatically generated. Changes:
+# - add xz package
+#
+# Kernel config based on: arch/arm/configs/lx_anzu_defconfig
+# - apply patches to compile
+# - make kernel XZ-compressed instead of LZMA-compressed
 
-# Unsure if pkgrel is correct...
-
-_vendor=semc
-_flavor=semc-anzu
-_hash="1495bfcf93f9e0e896331f29e1850387c31d6714"
-_config="config-${_flavor}.armhf"
-
-pkgname=linux-${_flavor}
-pkgver=4.4.67
-case $pkgver in
-	*.*.*)  _kernver=${pkgver%.*};;
-	*.*) _kernver=$pkgver;;
-esac
-pkgrel=2
+pkgname="linux-semc-anzu"
+pkgver=3.4.0
+pkgrel=0
+pkgdesc="Xperia Arc/Arc S kernel fork"
 arch="armhf"
-pkgdesc="AOSP based kernel for msm7x30 devices"
-url="https://github.com/msm7x30/android_kernel_qcom_msm7x30"
-depends="postmarketos-mkinitfs"
-makedepends="perl sed installkernel bash gmp-dev bc linux-headers elfutils-dev"
-options="!strip !check !tracedeps"
-install=
-source="
-	$pkgname-$_hash.zip::https://github.com/msm7x30/android_kernel_qcom_msm7x30/archive/android-4.4.zip
-	$_config
-	compiler-gcc6.h
-"
-subpackages=""
-license="GPL2"
-
-_abi_release=${pkgver}
 _carch="arm"
+_flavor="semc-anzu"
+url="https://kernel.org"
+license="GPL2"
+options="!strip !check !tracedeps"
+makedepends="perl sed installkernel bash gmp-dev bc linux-headers elfutils-dev xz"
 HOSTCC="${CC:-gcc}"
 HOSTCC="${HOSTCC#${CROSS_COMPILE}}"
 
-ksrcdir="$srcdir/android_kernel_qcom_msm7x30-android-4.4"
+# Source
+_repository="android_kernel_semc_msm7x30"
+_commit="9c6f07f81e2c0bcb2bef75fa9716cc30f8942286"
+_config="config-${_flavor}.${arch}"
+source="
+	$pkgname-$_commit.tar.gz::https://github.com/LegacyXperia/${_repository}/archive/${_commit}.tar.gz
+	$_config
+	compiler-gcc6.h
+	01_msm-fix-perf_trace_counters.patch
+	02_gpu-msm-fix-gcc5-compile.patch
+"
+builddir="$srcdir/${_repository}-${_commit}"
 
 prepare() {
-	local _patch_failed=
-	cd "$ksrcdir"
-
-	# first apply patches in specified order
-	for i in $source; do
-		case $i in
-		*.patch)
-			msg "Applying $i..."
-			if ! patch -s -p1 -N -i "$srcdir"/$i; then
-				echo $i >>failed
-				_patch_failed=1
-			fi
-			;;
-		esac
-	done
-
-	if ! [ -z "$_patch_failed" ]; then
-		error "The following patches failed:"
-		cat failed
-		return 1
-	fi
+	default_prepare
 
 	# gcc6 support
-	cp -v "$srcdir/compiler-gcc6.h" "$ksrcdir/include/linux/"
+	cp -v "$srcdir/compiler-gcc6.h" "$builddir/include/linux/"
 
-	mkdir -p "$srcdir"/build
-	cp "$srcdir"/$_config "$srcdir"/build/.config || return 1
-	make -C "$ksrcdir" O="$srcdir"/build ARCH="$_carch" HOSTCC="$HOSTCC" \
-		silentoldconfig
+	# Remove -Werror from all makefiles
+	find . -type f -name Makefile -print0 | \
+		xargs -0 sed -i 's/-Werror-/-W/g'
+	find . -type f -name Makefile -print0 | \
+		xargs -0 sed -i 's/-Werror//g'
+
+	# Prepare kernel config ('yes ""' for kernels lacking olddefconfig)
+	cp "$srcdir"/$_config "$builddir"/.config
+	yes "" | make ARCH="$_carch" HOSTCC="$HOSTCC" oldconfig
 }
 
-
-
-# this is so we can do: 'abuild menuconfig' to reconfigure kernel
 menuconfig() {
-	cd "$srcdir"/build || return 1
+	cd "$builddir"
 	make ARCH="$_carch" menuconfig
 	cp .config "$startdir"/$_config
 }
 
 build() {
-	cd "$srcdir"/build
 	unset LDFLAGS
 	make ARCH="$_carch" CC="${CC:-gcc}" \
-		KBUILD_BUILD_VERSION="$((pkgrel + 1 ))-Alpine" \
-		|| return 1
+		KBUILD_BUILD_VERSION="$((pkgrel + 1 ))-postmarketOS"
 }
 
 package() {
-	install -Dm644 "$srcdir/build/arch/arm/boot/zImage" \
-		"$pkgdir/boot/vmlinuz-$_flavor"
-
-	install -D "$srcdir/build/include/config/kernel.release" \
+	# kernel.release
+	install -D "$builddir/include/config/kernel.release" \
 		"$pkgdir/usr/share/kernel/$_flavor/kernel.release"
+
+	# zImage (find the right one)
+	cd "$builddir/arch/$_carch/boot"
+	_target="$pkgdir/boot/vmlinuz-$_flavor"
+	for _zimg in zImage-dtb Image.gz-dtb *zImage Image; do
+		[ -e "$_zimg" ] || continue
+		msg "zImage found: $_zimg"
+		install -Dm644 "$_zimg" "$_target"
+		break
+	done
+	if ! [ -e "$_target" ]; then
+		error "Could not find zImage in $PWD!"
+		return 1
+	fi
 }
 
-sha512sums="f3bca9f9f184e85ec353876d90bcafa3782ee55499132c9f434a9b3e682eaff6e55298bd428445ec5a25d986434db406d541e165ce66a867106035cf3a28075f  linux-semc-anzu-1495bfcf93f9e0e896331f29e1850387c31d6714.zip
-abc46c4a764e08cbf24c517b4087910138e349eb2c5b3496c0bd62f3057ed11368510846938cd675c85051c8955774f9120f42829bc81152c98374bb2261671f  config-semc-anzu.armhf
-d80980e9474c82ba0ef1a6903b434d8bd1b092c40367ba543e72d2c119301c8b2d05265740e4104ca1ac5d15f6c4aa49e8776cb44264a9a28dc551e0d1850dcc  compiler-gcc6.h"
+sha512sums="234e8973236e6056c60a312340ef4ccb7598adc43bd1f0c2ca0e89d03f4e16ecfdd5ad4658d76993c7bae24242a7e134a9ed2fda662dfe229b61f3a88ea6c2f0  linux-semc-anzu-9c6f07f81e2c0bcb2bef75fa9716cc30f8942286.tar.gz
+0af76d035ce554139f58ca1c424ac3d9a30dab63dc4ea40c524bb15a2b610687a98f07caf734bd6b138f1a06b543f1be668fee89250ba1fd47dbd7ec15e59780  config-semc-anzu.armhf
+d80980e9474c82ba0ef1a6903b434d8bd1b092c40367ba543e72d2c119301c8b2d05265740e4104ca1ac5d15f6c4aa49e8776cb44264a9a28dc551e0d1850dcc  compiler-gcc6.h
+f85ced49ee2f2461adea68dac0a10452aa809a7d41d869092d94eb085344919a9a385dec0c48011f4601ca4f441700f7fe49075c7eca4fb2d66b01f7d413ccb7  01_msm-fix-perf_trace_counters.patch
+7be03a9e78b7ac330a54b1f00509caa0621a95c0c55901878ad757f9dd69cc05ba2c8b5ea987063ae1224f92c4d090d515fa5d369e7755181a4871b0d0f82881  02_gpu-msm-fix-gcc5-compile.patch"
